### PR TITLE
Allow specifying options as environment variables

### PR DESCRIPTION
**Pull request by deshipu**
So that we can do:

```bash
$ export AMPY_PORT=/dev/ttyUSB0
$ ampy ls
```

### CODE REVIEW

**Comment by tdicola** [comment]
Oh awesome thanks for the pull!  Actually can you try it today setting either AMPY_PORT and/or AMPY_BAUD (it defaults to 115200 though)?  The way I use the click framework with the envvar variable here it actually should do the environment variable fallback automatically: https://github.com/adafruit/ampy/blob/master/ampy/cli.py#L35-L40  Let me know if that isn't working for some reason though (seems to work on OSX).

**Comment by tdicola** [comment]
That said I should probably document these in the doc string & generated usage info. :)

**Comment by deshipu** [comment]
You are right, I didn't even test it, assuming it's not enabled. Sorry for wasting your time.

**Comment by tdicola** [comment]
Oh no worries, thanks for bringing it up!  It should be mentioned in the docstring & generated usage now with a change I made a couple days ago too.

**Pull request closed without merging**
