### PR TITLE
ampy/cli: Implement 'ampy reset --bootloader' and friends

### PR DESCRIPTION
**Pull request by jepler**
This adds a command to enter the bootloader without physical interaction with the target board.  It's handy when testing new circuitpython software builds and you want to use the uf2 uploader.

(note that entering the bootloader in this way has been broken in the master branch of circuitpython, see adafruit/circuitpython#739, but it works in 2.x and should work again once #740 is merged)

### CODE REVIEW

**Comment by jepler** [comment]
One alternative to this would be to add `ampy reset --bootloader` instead.  It bothers me a bit that `bootloader` appears at the head of a `ampy --help` even though it's going to be rarely used compared to the other options.

**Comment by osterwood** [comment]
I like the idea of this existing as an option flag on the reset command.  No need to pollute the global help message with a feature that will be used so infrequently.

**Comment by tannewt** [comment]
`ampy reset --bootloader` works for me.

**Comment by tannewt** [comment]
Probably fix #38 at the same time.

**Comment by ladyada** [comment]
kk @jepler do you want commit access to this repo? you'll be testing it more than me :)

**Comment by jepler** [comment]
@ladyada I'm flattered by your offer and would treat the privilege with respect, but I feel I'd also benefit from oversight on my proposed changes like I've gotten from tannewt and dhalbert in the main circuitpython project.

----

After another refresh, I think this commit "works", in that the default mode does just what it did before, and `--bootloader`, `--hard`, and `--safe` invoke the methods provided in the `microcontroller` module for resetting in the given mode.

However, there are some caveats, based on my testing with a Trinket M0:
 * Bugs in CP2.x and master branch prevent the new modes from working (I still haven't gotten the "safe mode" to work, I don't think, but patches to make hard and bootloader reboot work properly on trinket m0 should show up in an adafruit/circuitpython PR soon)
 * At least in CP master branch (I didn't return to 2.x to test this), the old mode doesn't re-run main.py, it drops into the (cooked) repl, so I renamed the flag to "--repl" and called it a day.

On an Feather HUZZAH ESP8266 with CP2.x, the unsupported modes get a nice useful message, so that's nice.  E.g.,:
```
$ ampy -p /dev/ttyUSB0 reset --safe
ESP8226 does not support safe mode.
```

**Comment by jepler** [comment]
I don't specifically have micropython on any boards at this time.  I have an stm32 "discovery" board at the bottom of a junk pile somewhere, which might turn out to be supported.  I'll look into that.

Since the lines to 'import microcontroller' aren't used unless you specify a non-default reset flag, it doesn't immediately break if the module's not there, the enhanced feature is just not supported.  The error message could be better, however (you'd get an ugly python exception)

**Comment by tannewt** [comment]
Yup, something like that will work.

**Comment by jepler** [comment]
I've updated this pull request again.  Testing performed on Trinket M0 with CP3.0alpha (all modes but safe work, seems to be CP3.0 bug) and PyBoard 1.1 with MicroPython v1.9.3 (--repl [default] and --hard work, other modes are rejected with a message); I can test with newer MP on the PyBoard if that is desired.

**Pull request merged**
