### PR TITLE
Load environment variables from .ampy config file

### PR DESCRIPTION
**Pull request by garthk**
Fill in a `.ampy` file in your working directory, one of its parents, or your home directory to set `AMPY_PORT` *et al* just how you like it:

    # Example .ampy file
    # Please fill in your own port, baud rate, and delay
    AMPY_PORT=/dev/cu.wchusbserial1410
    AMPY_BAUD=115200
    AMPY_DELAY=0.5 # Fix for macOS users' "Could not enter raw repl"

### CODE REVIEW

**Comment by jerryneedell** [comment]
I tried install downloading the PR and installing via:
sudo python setup.py install

now any attempt to run ampy yields:
```
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/ampy$ ampy
Traceback (most recent call last):
  File "/usr/local/bin/ampy", line 9, in <module>
    load_entry_point('adafruit-ampy==1.0.4', 'console_scripts', 'ampy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/ampy/cli.py", line 34, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_dotenv-0.8.2-py2.7.egg/dotenv/main.py", line 237, in find_dotenv
    for dirname in _walk_to_root(path):
  File "/usr/local/lib/python2.7/dist-packages/python_dotenv-0.8.2-py2.7.egg/dotenv/main.py", line 210, in _walk_to_root
    raise IOError('Starting path not found')
IOError: Starting path not found
```

I am using Ubuntu 16.04 Linux

**Comment by jerryneedell** [comment]
Reverting back to ampy master (1.0.4)  works normally.

**Comment by garthk** [comment]
@jerryneedell that failure's in `dotenv`. I'll see if I can nut out where.

**Comment by garthk** [comment]
Oh, nice. With the module installed by `python setup.py install`, `dotenv` was trying to resolve via the virtual path inside the egg. I've fixed it by insisting on resolution via the current directory, which I'd assumed was how it'd always work. @jerryneedell please verify, if you don't mind a second crack?

**Comment by jerryneedell** [comment]
Thank you! I tried it with a feather52832 -- (requires a 1.5 second delay) and it seems to work well:
```
lib
sdmount_lib.py
ble_scan.py
sdmount.py
jerryneedell@Ubuntu-Macmini:~/projects/feather52$ cat .ampy
# Example .ampy file
# Please fill in your own port, baud rate, and delay
AMPY_PORT=/dev/ttyUSB0
AMPY_BAUD=115200
AMPY_DELAY=1.5 
```
Minor note: the example in your first post implies you can put a comment on a line in the .ampy file with a "#" but this caused an error for me. Was that a typo in the example or bug?
```
jerryneedell@Ubuntu-Macmini:~/projects/feather52$ ampy ls
Usage: ampy [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "--delay" / "-d": 1.5  # comment is not a valid floating point value
jerryneedell@Ubuntu-Macmini:~/projects/feather52$ cat .ampy
# Example .ampy file
# Please fill in your own port, baud rate, and delay
AMPY_PORT=/dev/ttyUSB0
AMPY_BAUD=115200
AMPY_DELAY=1.5  # comment

```

**Comment by ladyada** [comment]
ok should we merge?

**Comment by ladyada** [comment]
yeah i will bump the version!

**Comment by ladyada** [comment]
bumped in pypi, plz try pip3'ing it!

**Comment by jerryneedell** [comment]
on linux - sudo pip3 install adafruit-ampy worked -- got 1.0.5
had to uninstall previous versions first.

**Comment by garthk** [comment]
@jerryneedell good catch on the comment. Will fix.

**Pull request merged**
